### ISSUE TITLE
Wingie2 TRS audio output question

### ISSUE THREAD

**Issue by m-r-m-s** [mengqimusic/Wingie2#10]
@mengqimusic I am on the latest firmware (v3.1) and I notice the following behavior with the TRS output with either an external sound source attached to the line input or when using the Wingie2 Mic.

Perhaps others using the latest firmware version can confirm same behavior?

- When I am using headphones from the 3.5mm Stereo TRS audio output, I can hear both L & R resonators.

- When I use a [TRS to Dual TS cable](https://www.sweetwater.com/store/detail/CMR203--hosa-cmr-203-stereo-breakout-3.5mm-trs-to-dual-rca-3-foot) from the 3.5mm Stereo TRS audio output, I can hear both L&R resonators

- When I use any TRS to TRS cable from the Wingie2 TRS audio output I can only hear the Left resonator but not the Right resonator (I also tried adjusting threshold intensity as well as pre / post clipper gain and this has no impact in output from the Right resonator).

Is this the correct TRS output behavior for the output? The manual states “Wingie2 audio output is 3.5mm Stereo TRS”

Forgive my ignorance in advance as I expected a Stereo TRS to TRS cable attached to the audio output of the Wingie2 would be able to output both L & R resonator signals.

Any insights would be greatly appreciated. Thanks again for such an amazing instrument =)

**Comment by DaveSeidel** [comment]
There is no difference between these different output cable types as far as the device is concerned: they all connect to the Wingie2 using 3.5mm TRS. Wingie2 has no way to distinguish between them. Also, the latest firmware did not include any changes in the audio output handling.

**Comment by m-r-m-s** [comment]
Thanks for confirming. I must have something going on with my cabling or setup after the signal leaves the wingie2
