### ISSUE TITLE
USB MIDI on Wingie II?

### ISSUE THREAD

**Issue by finnglink** [mengqimusic/Wingie2#9]
Hey!
This is more a feature request than an issue:
Is USB-MIDI possible hardware-wise? The code part shouldn't much different, if the hardware allows it.
I'd love to plug this into my Norns with just one cable for MIDI and power :)

Thank you!

**Comment by mengqimusic** [comment]
Hi! MIDI over USB is impossible hardware-wise because the USB-Serial chip there is hardcoded. Thank you.
